name: go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3 # https://github.com/actions/setup-go
      with:
        go-version-file: './go.mod' # use mod file go version explicitly
        check-latest: false 
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
