# This is a basic workflow to help you get started with Actions
name: python
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # add capability to manually run this action, see https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
      - uses: actions/setup-python@v5 # https://github.com/actions/setup-python
        with:
          python-version: '3.x'
      - name: install pytest
        run: |
          pip install -r requirements.txt
          python --version
          pytest --version
          echo "PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH" >> $GITHUB_ENV
      - name: Run pytest
        run: | 
          echo "PYTHONPATH=$PYTHONPATH"
          pytest
